import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import ReduxProvider from "@/components/ReduxProvider";
import { Footer } from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-new-gr-c-s-check-loaded="14.1270.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
      >
        <ReduxProvider>
          <Navbar />
          {children}
          <Toaster position="bottom-center" reverseOrder={false} />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
